[build]
  # Build the frontend with explicit production mode
  command = "cd moviemap && npm install && NODE_ENV=production VITE_MODE=production npx vite build --mode production"
  publish = "moviemap/dist"
  functions = "netlify/functions"

# Map /api/* requests to the direct Netlify Function FIRST
# This needs to be BEFORE the SPA redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-direct/:splat"
  status = 200
  force = true
  
# Also create a direct path to the API function
[[redirects]]
  from = "/api-direct/*"
  to = "/.netlify/functions/api-direct/:splat"
  status = 200
  force = true

# Handle SPA routing for the frontend
# This must come AFTER the API redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Force production mode for the frontend build
  NODE_ENV = "production"
  # Disable secrets scanning for the Mapbox token
  SECRETS_SCAN_OMIT_KEYS = "VITE_MAPBOX_TOKEN"