[build]
  # Build the frontend with explicit production mode
  command = "npm install && cd moviemap && npm install && NODE_ENV=production VITE_MODE=production npx vite build --mode production"
  publish = "moviemap/dist"
  functions = "./moviemap/netlify/functions"

# Installing function dependencies from root package.json
# No plugins needed anymore

# Map /api/* requests to the Netlify Function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle SPA routing for the frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Force production mode for the frontend build
  NODE_ENV = "production"
  # Set API URL for production
  VITE_API_URL = "https://moviemaps.net/api"
  # Disable secrets scanning for the Mapbox token
  SECRETS_SCAN_OMIT_KEYS = "VITE_MAPBOX_TOKEN FIREBASE_SERVICE_ACCOUNT_JSON"# Updated on Mon May  5 17:08:35 CDT 2025
