[build]
  # Build the frontend with explicit production mode
  command = "cd moviemap && npm install && NODE_ENV=production VITE_MODE=production npx vite build --mode production"
  publish = "moviemap/dist"

# Handle SPA routing for the frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Force production mode for the frontend build
  NODE_ENV = "production"
  # Disable secrets scanning for the Mapbox token
  SECRETS_SCAN_OMIT_KEYS = "VITE_MAPBOX_TOKEN"