[build]
  # Directory to change to before starting a build
  base = "moviemap/"
  
  # Directory that contains the deploy-ready HTML files
  publish = "dist"
  
  # Default build command
  command = "npm run build"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200