[build]
  # Directory that contains the deploy-ready HTML files
  publish = "dist"
  
  # Default build command
  command = "npm run build"
  
  # Configure environment
  [build.environment]
    # Disable secrets scanning for the Mapbox token
    SECRETS_SCAN_OMIT_KEYS = "VITE_MAPBOX_TOKEN"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200